### ISSUE TITLE
Its not wokring with Rxswift4.0, Can you update this ?

### ISSUE THREAD

**Issue by jayesh1991** [bmoliveira/RxReachability#3]

**Comment by nsleader** [comment]
+1

**Comment by yotamoo** [comment]
I saw that you've updated, but I can't install version 0.1.4
Maybe you forgot to add the right tag?

Great work, thanks

**Comment by mehdok** [comment]
+1

**Comment by rnkyr** [comment]
Hello, @ivanbruel!
Looks like you've updated `master` branch, but haven't updated CocoaPod repo.
So this `pod 'RxReachability', '~> 0.1.4'` doesn't work

Thanks for the lib.

**Comment by bystritskiy** [comment]
+1

**Comment by maslovsa** [comment]
@ivanbruel 
Could you please 

> pod trunk push RxReachability.podspec

**Comment by maslovsa** [comment]
And add 0.1.14 tag to the latest commit

**Comment by maslovsa** [comment]
While you're waiting for updates - you can use     
`pod 'RxReachability', :git => 'https://github.com/bmoliveira/RxReachability', :commit => 'c44437e'`

**Comment by LightMan** [comment]
Thanks @maslovsa.
@bmoliveira Bruno please,  add 0.1.4tag and pod trunk push RxReachability.podspec

**Comment by bmoliveira** [comment]
Sorry for the delay, but the project recently was transferred to me and now I have the proper notifications on it 😱 

From now on I'll keep a close look on the pending issues and on new features
